### ISSUE TITLE
website appears offline

### ISSUE THREAD

**Issue by dylan-k** [gewgaws/git-for-writers#2]
the website at http://gewga.ws/git-for-writers/ appears to be offline. Does this project need a new home?

**Comment by dylan-k** [comment]
No reply? I'll assume this is a dead project. I've reposted the site to http://nocategories.net/git-for-writers/ and have forked a version at https://github.com/dylan-k/git-for-writers

**Comment by katrinleinweber** [comment]
Another live version is on https://katrinleinweber.github.io/git-for-writers/ now and I included @lambo's ["repaired navigation links"](https://github.com/gewgaws/git-for-writers/pull/1).
